all:
	#TODO conditional for machine
	g++ -DNUMT=1 -o proj0 main.cpp -lm -fopenmp
	#g++ -DNUMT=1 -o proj0 main.cpp -lm -fopenmp
	./proj0
	g++ -DNUMT=4 -o proj0 main.cpp -lm -fopenmp
	#g++ -DNUMT=4 -o proj0 main.cpp -lm -fopenmp
	./proj0
clean:
	rm proj0
